# Makefile to collect all C source files of src/ble

SRC_BLE_FILES = \
    ancs_client.c \
    att_db.c \
    att_db_util.c \
    att_dispatch.c \
    att_server.c \
    battery_service_client.c \
    device_information_service_client.c \
    gatt_client.c \
    hids_client.c \
    le_device_db_memory.c \
    le_device_db_tlv.c \
    sm.c \

