# Makefile to collect all C source files of src/ble

SRC_BLE_FILES = \
    att_server.c \
    ancs_client.c \
    att_dispatch.c \
    sm.c \
    att_db_util.c \
    le_device_db_memory.c \
    le_device_db_tlv.c \
    att_db.c \
    gatt_client.c \

