obj-y += \
        sbc_analysis.o           \
        sbc_dct.o                \
        sbc_dct_coeffs.o         \
        sbc_enc_bit_alloc_mono.o \
        sbc_enc_bit_alloc_ste.o  \
        sbc_enc_coeffs.o         \
        sbc_encoder.o            \
        sbc_packing.o            \

ccflags-y += -I${ZEPHYR_BASE}/subsys/btstack/bluedroid/encoder/include
