obj-y +=  \
	ad_parser.o \
	btstack_linked_list.o \
	btstack_memory.o \
	btstack_memory_pool.o \
	btstack_ring_buffer.o \
	btstack_run_loop.o \
	btstack_util.o \
	hci.o \
	hci_cmd.o \
	hci_dump.o \
	l2cap.o \
	l2cap_signaling.o \

obj-y += ble/
# obj-y += classic/
# obj-y += bluedroid/

ccflags-y += -I${ZEPHYR_BASE}/subsys/btstack
ccflags-y += -I${ZEPHYR_BASE}/ext/hal/nordic/mdk
