obj-y +=  \
	ancs_client.o \
	att_db.o \
	att_dispatch.o \
	att_server.o \
	gatt_client.o \
	le_device_db_memory.o \
	sm.o \
	sm_mbedtls_allocator.o \

#	att_db_util.o \

obj-y += gatt-service/
ccflags-y += -I${ZEPHYR_BASE}/subsys/btstack
