obj-y +=  \
	ad_parser.o \
	btstack_linked_list.o \
	btstack_memory.o \
	btstack_memory_pool.o \
	btstack_ring_buffer.o \
	btstack_run_loop.o \
	btstack_slip.o \
	btstack_util.o \
	hci.o \
	hci_cmd.o \
	hci_dump.o \
	hci_transport_h4.o \
	hci_transport_h5.o \
	l2cap.o \
	l2cap_signaling.o \
	btstack_run_loop_embedded.o \

obj-y += ble/
ccflags-y += -I${ZEPHYR_BASE}/subsys/btstack
