obj-y += \
        alloc.o \
        bitalloc.o \
        bitalloc-sbc.o \
        bitstream-decode.o \
        decoder-oina.o \
        decoder-private.o \
        decoder-sbc.o \
        dequant.o \
        framing.o \
        framing-sbc.o \
        oi_codec_version.o \
        synthesis-sbc.o \
        synthesis-dct8.o \
        synthesis-8-generated.o \

ccflags-y += -I${ZEPHYR_BASE}/subsys/btstack/bluedroid/decoder/include
