#!/usr/bin/env python3
#
# Generate Zephyr board-specific Kconfig fragments for tested boards.
#
# The generated files are committed intentionally. Re-run this script after
# changing nordic_sdc.conf or TESTED_NORDIC_BOARDS below.

from pathlib import Path


GENERATED_HEADER = """\
# Generated by generate_board_configs.py. Do not edit manually.
#
# Update nordic_sdc.conf and re-run the generator when these settings need to
# change.

"""


TESTED_NORDIC_BOARDS = [
    "nrf52dk/nrf52832",
    "nrf52840dk/nrf52840",
    "nrf5340dk/nrf5340/cpuapp",
    "nrf54l15dk/nrf54l15/cpuapp",
    "nrf54lm20dk/nrf54lm20a/cpuapp",
]


def board_conf_filename(board_target):
    return board_target.replace("/", "_") + ".conf"


def main():
    zephyr_port_dir = Path(__file__).resolve().parent
    boards_dir = zephyr_port_dir / "boards"
    boards_dir.mkdir(exist_ok=True)

    nordic_sdc_config = (zephyr_port_dir / "nordic_sdc.conf").read_text()
    content = GENERATED_HEADER + nordic_sdc_config.rstrip() + "\n"
    for board_target in TESTED_NORDIC_BOARDS:
        output_path = boards_dir / board_conf_filename(board_target)
        output_path.write_text(content)
        print(output_path.relative_to(zephyr_port_dir))


if __name__ == "__main__":
    main()
