# Makefile to collect all C source files of src/ble/gatt-service

SRC_BLE_GATT_SERVICE_FILES = \
    ancs_client.c \
    audio_input_control_service_server.c \
    battery_service_client.c \
    battery_service_server.c \
    bond_management_service_server.c \
    broadcast_audio_scan_service_client.c \
    broadcast_audio_scan_service_util.c \
    broadcast_audio_scan_service_server.c \
    cycling_power_service_server.c \
    cycling_speed_and_cadence_service_server.c \
    device_information_service_client.c \
    device_information_service_server.c \
    heart_rate_service_server.c \
    hids_client.c \
    hids_device.c \
    le_audio_util.c \
    mesh_provisioning_service_server.c \
    mesh_proxy_service_server.c \
    microphone_control_service_server.c \
    nordic_spp_service_server.c \
    scan_parameters_service_client.c \
    scan_parameters_service_server.c \
    tx_power_service_server.c \
    ublox_spp_service_server.c \
    volume_control_service_server.c \
    volume_offset_control_service_server.c \
