# Makefile to collect all C source files of src/ble/gatt-service

SRC_BLE_GATT-SERVICE_FILES = \
    battery_service_server.c \
    device_information_service_server.c \
	heart_rate_service_server.c \
    hids_device.c \

