# Makefile to collect all C source files of src/ble/gatt-service

SRC_BLE_GATT_SERVICE_FILES = \
    ancs_client.c \
    battery_service_client.c \
    battery_service_server.c \
    bond_management_service_server.c \
    cycling_power_service_server.c \
    cycling_speed_and_cadence_service_server.c \
    device_information_service_client.c \
    device_information_service_server.c \
    heart_rate_service_server.c \
    hids_client.c \
    hids_device.c \
    nordic_spp_service_server.c \
    scan_parameters_service_client.c \
    scan_parameters_service_server.c \
    tx_power_service_server.c \
    ublox_spp_service_server.c \
