language: c
os: linux
sudo: required

matrix:
  include:
    - compiler: gcc-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - check
            - libsubunit-dev
            - gcc-7
            - ninja-build
            - doxygen
      env:
        - LSAN_OPTIONS=verbosity=1:log_threads=1

    - compiler: clang-7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - check
            - libsubunit-dev
            - clang-7
            - ninja-build
            - doxygen
      env:
        - LSAN_OPTIONS=verbosity=1:log_threads=1

before_install:
  # Install cmake
  - wget -O cmake.sh https://cmake.org/files/v3.12/cmake-3.12.0-Linux-x86_64.sh
  - sudo sh cmake.sh --skip-license --exclude-subdir --prefix=/usr/local

script:
  - ./travis.sh
