#!/usr/bin/env python3
#
# Create tool/cmake/BTstackSources.cmake: source file lists for CMake consumers.
# Copyright 2026 BlueKitchen GmbH
#
# This generates CMake source lists for BTstack.
#
# Lists are grouped so a consumer can take a whole list or skip it.
# The aim is that it should not be necessary to pick files out of a source list.
# Anything mutually exclusive - transports, link key / device db backends,
# TLV backends, run loops, codecs, etc. has its own list.
#
# Files that no rule matches are listed in BTSTACK_UNCLASSIFIED_SOURCES and
# reported on stderr, so a consumer can check that the lists it expects still exist.
#
# Usage:
#   python3 tool/create_cmake_sources.py
#
# Re-run after adding source files.
# CI can check that running the tool has no effect.

import os
import re
import sys

HEADER = """# Source file lists for BTstack, for CMake based consumers.
#
# GENERATED by tool/create_cmake_sources.py -- do not edit.
#
# Lists are grouped so a consumer can take a whole list or skip it.
# The aim is that it should not be necessary to pick files out of a source list.
# Anything mutually exclusive - transports, link key / device db backends,
# TLV backends, run loops, codecs, etc. has its own list.
#
# BTSTACK_SOURCE_LISTS names every list defined here, so a consumer can check
# that the lists it expects still exist.
#
# Paths are relative to BTSTACK_ROOT, for example:
#
#   include(${BTSTACK_ROOT}/tool/cmake/BTstackSources.cmake)
#   list(TRANSFORM BTSTACK_CORE_SOURCES PREPEND "${BTSTACK_ROOT}/")
#   target_sources(my_port PRIVATE ${BTSTACK_CORE_SOURCES})

"""

# Ordered; first match wins. In patterns, '*' matches within one path segment
# and '**' matches any number of segments
#
# A name ending in '*' means one list per matched file, with the trailing '*'
# replaced by the file's basename.
RULES = [
    # pick at most one, or supply your own
    ("src/hci_transport_h4.c",                          "TRANSPORT_H4"),
    ("src/hci_transport_h5.c",                          "TRANSPORT_H5"),
    ("src/hci_transport_em9304_spi.c",                  "TRANSPORT_EM9304_SPI"),
    ("src/btstack_uart_slip_wrapper.c",                 "TRANSPORT_SLIP"),
    ("platform/embedded/btstack_em9304_spi_embedded.c", "TRANSPORT_EM9304_SPI_EMBEDDED"),

    ("src/classic/btstack_link_key_db_memory.c",        "LINK_KEY_DB_MEMORY"),
    ("src/classic/btstack_link_key_db_static.c",        "LINK_KEY_DB_STATIC"),
    ("src/classic/btstack_link_key_db_tlv.c",           "LINK_KEY_DB_TLV"),
    ("src/ble/le_device_db_memory.c",                   "LE_DEVICE_DB_MEMORY"),
    ("src/ble/le_device_db_tlv.c",                      "LE_DEVICE_DB_TLV"),
    ("src/btstack_tlv_none.c",                          "TLV_NONE"),
    ("platform/embedded/btstack_tlv_flash_bank.c",      "TLV_FLASH_BANK"),
    ("platform/embedded/hal_flash_bank_memory.c",       "HAL_FLASH_BANK_MEMORY"),

    ("platform/embedded/btstack_run_loop_embedded.c",   "RUN_LOOP_EMBEDDED"),

    # optional add-ons, one list each
    ("platform/embedded/btstack_stdin_embedded.c",      "STDIN_EMBEDDED"),
    ("platform/embedded/btstack_uart_block_embedded.c", "UART_BLOCK_EMBEDDED"),
    ("platform/embedded/btstack_audio_embedded.c",      "AUDIO_EMBEDDED"),
    ("platform/lwip/bnep_lwip.c",                       "BNEP_LWIP"),
    ("platform/lwip/port/*.c",                          "LWIP_PORT"),

    ("src/hci_dump_buffered.c",                         "HCI_DUMP_BUFFERED"),
    ("src/hci_dump_dispatch.c",                         "HCI_DUMP_DISPATCH"),
    ("platform/embedded/hci_dump_embedded_stdout.c",    "HCI_DUMP_EMBEDDED_STDOUT"),
    ("platform/embedded/hci_dump_segger_rtt_stdout.c",  "HCI_DUMP_SEGGER_RTT_STDOUT"),
    ("platform/embedded/hci_dump_segger_rtt_binary.c",  "HCI_DUMP_SEGGER_RTT_BINARY"),

    # codecs
    ("src/classic/btstack_sbc_encoder_bluedroid.c",     "SBC_ENCODER"),
    ("3rd-party/bluedroid/encoder/**",                  "SBC_ENCODER"),
    ("src/classic/btstack_sbc_decoder_bluedroid.c",     "SBC_DECODER"),
    ("3rd-party/bluedroid/decoder/**",                  "SBC_DECODER"),
    ("src/classic/btstack_sbc_bluedroid.c",             "SBC_COMMON"),
    ("src/classic/btstack_cvsd_plc.c",                  "CVSD_PLC"),
    ("src/classic/hfp_msbc.c",                          "HFP_MSBC"),
    ("src/classic/hfp_codec.c",                         "HFP_CODEC"),

    # feature areas, taken whole
    ("src/mesh/**",                                     "MESH"),
    ("src/le-audio/*",                                  "LE_AUDIO"),
    ("src/btstack_lc3*.c",                              "LE_AUDIO"),

    # which GATT services an application wants is an application choice
    ("src/ble/gatt-service/*.c",                        "GATT_SERVICE_*"),

    # BNEP is only wanted alongside a network stack
    ("src/classic/bnep.c",                              "BNEP"),

    # OBEX client and server are selected independently
    ("src/classic/obex_srm_client.c",                   "OBEX_SRM_CLIENT"),
    ("src/classic/obex_srm_server.c",                   "OBEX_SRM_SERVER"),

    # optional helpers; nothing in CORE requires them
    ("src/btstack_fsm.c",                               "UTIL_*"),
    ("src/btstack_hsm.c",                               "UTIL_*"),
    ("src/btstack_chunk_buffer.c",                      "UTIL_*"),
    ("src/btstack_linked_queue.c",                      "UTIL_*"),
    ("src/btstack_ltv_builder.c",                       "UTIL_*"),
    ("src/btstack_tlv_builder.c",                       "UTIL_*"),
    ("src/btstack_sample_rate_compensation.c",          "UTIL_*"),
    ("src/btstack_base64_encoder.c",                    "UTIL_*"),
    ("src/btstack_resample.c",                          "UTIL_*"),
    ("src/btstack_audio_*.c",                           "AUDIO_DEMO"),

    # take whole
    ("src/ble/*.c",                                     "BLE"),
    ("src/classic/*.c",                                 "CLASSIC"),
    ("3rd-party/segger-rtt/SEGGER_RTT_Syscalls_GCC.c",  "SEGGER_RTT_SYSCALLS_GCC"),
    ("3rd-party/segger-rtt/SEGGER_RTT_Syscalls_IAR.c",  "SEGGER_RTT_SYSCALLS_IAR"),
    ("3rd-party/segger-rtt/SEGGER_RTT_Syscalls_KEIL.c", "SEGGER_RTT_SYSCALLS_KEIL"),
    ("3rd-party/segger-rtt/SEGGER_RTT_Syscalls_SES.c",  "SEGGER_RTT_SYSCALLS_SES"),
    ("3rd-party/**",                                    "THIRD_PARTY_*"),
    ("src/*.c",                                         "CORE"),
]

# Directories scanned. Other platform/ and port/ directories are port specific
SCAN = ["src", "platform/embedded", "platform/lwip", "3rd-party"]

# Third party projects ship their own tests and examples
SKIP_DIRS = {"test", "tests", "example", "examples", "doc", "docs"}


def matches(rel, pattern):
    """Glob match where '*' stays within a path segment and '**' spans segments."""
    regex = ""
    i = 0
    while i < len(pattern):
        if pattern.startswith("**", i):
            regex += ".*"
            i += 2
        elif pattern[i] == "*":
            regex += "[^/]*"
            i += 1
        else:
            regex += re.escape(pattern[i])
            i += 1
    return re.fullmatch(regex, rel) is not None


def list_name(rule_name, rel):
    if not rule_name.endswith("*"):
        return rule_name
    if rule_name.startswith("THIRD_PARTY"):
        key = rel.split("/")[1]
    else:
        key = os.path.basename(rel)[:-len(".c")]
        # UTIL_* etc read better without the btstack_ prefix repeated
        key = re.sub(r"^btstack_", "", key)
    return rule_name[:-1] + re.sub(r"[^A-Za-z0-9]", "_", key).upper()


def classify(rel):
    for pattern, name in RULES:
        if matches(rel, pattern):
            return list_name(name, rel)
    return None


def main():
    root = os.path.abspath(os.path.dirname(sys.argv[0]) + "/..")
    lists, unclassified = {}, []

    for scan in SCAN:
        for dirpath, dirnames, filenames in os.walk(os.path.join(root, scan)):
            dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
            for fn in sorted(filenames):
                if not fn.endswith(".c"):
                    continue
                rel = os.path.relpath(os.path.join(dirpath, fn), root).replace(os.sep, "/")
                name = classify(rel)
                if name is None:
                    unclassified.append(rel)
                else:
                    lists.setdefault(name, []).append(rel)

    out = os.path.join(root, "tool/cmake/BTstackSources.cmake")
    with open(out, "w") as f:
        f.write(HEADER)
        f.write("set(BTSTACK_SOURCE_LISTS\n")
        for name in sorted(lists):
            f.write("    %s\n" % name)
        f.write(")\n\n")
        for name in sorted(lists):
            f.write("set(BTSTACK_%s_SOURCES\n" % name)
            for rel in sorted(lists[name]):
                f.write("    %s\n" % rel)
            f.write(")\n\n")
        # Only emitted when non-empty: normally every source is in a list
        #   if (BTSTACK_UNCLASSIFIED_SOURCES)
        #       message(WARNING "BTstack has sources in no list")
        #   endif()
        if unclassified:
            f.write("# No rule in tool/create_cmake_sources.py matched these.\n")
            f.write("set(BTSTACK_UNCLASSIFIED_SOURCES\n")
            for rel in sorted(unclassified):
                f.write("    %s\n" % rel)
            f.write(")\n")

    print("wrote %s: %d lists, %d files" %
          (os.path.relpath(out, root), len(lists), sum(len(v) for v in lists.values())))
    if unclassified:
        print("WARNING: %d file(s) matched no rule:" % len(unclassified), file=sys.stderr)
        for rel in unclassified:
            print("   ", rel, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
