# Makefile to collect all C source files of src/le-audio/gatt-service

SRC_LE_AUDIO_GATT_SERVICE_FILES = \
    broadcast_audio_scan_service_client.c \
    broadcast_audio_scan_service_util.c \
    broadcast_audio_scan_service_server.c \
