# Makefile to collect all C source files of src/ble/gatt-service

SRC_BLE_GATT_SERVICE_FILES = \
    audio_input_control_service_server.c \
    broadcast_audio_scan_service_client.c \
    broadcast_audio_scan_service_util.c \
    broadcast_audio_scan_service_server.c \
    microphone_control_service_server.c \
    volume_control_service_server.c \
    volume_offset_control_service_server.c \
    